name: 'Cache .next folder'
description: 'Cache Next.js for faster application rebuilds.'
inputs:
  cwd:
    description: "Changes node's process.cwd() if the project is not located on the root. Default to process.cwd()"
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/${{ inputs.cwd }}/.next/cache
        key: |
          ${{ runner.os }}-nextjs-${{ inputs.cwd }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ inputs.cwd }}-
